[package]
name = "glock"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
html2md = "0.2.14"
schmargs = { git = "https://github.com/Property404/schmargs", version = "0.0.0" }
scraper = "0.18.1"
